name: 'Pattern Copy'
description: 'Pattern Copy'

inputs:
  github_token:  # id of input
    description: 'token'
    required: true
  source_repo:
    description: 'source repository'
    required: true
  dest_repo:
    description: 'destination repository'
    required: true

outputs:
  random-number: 
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps: 
    - name: Cloning Source Repo 
      run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash